"""complaints and timeline

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 15:49:10.061904

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("department", sa.String(length=20), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("ward_id", sa.Integer(), nullable=True),
        sa.Column("photo_path", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority_score", sa.Integer(), nullable=False),
        sa.Column("ai", sa.JSON(), nullable=True),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("merged_into_id", sa.Integer(), nullable=True),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ward_id"],
            ["wards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "ix_complaints_department_status", "complaints", ["department", "status"], unique=False
    )
    op.create_index("ix_complaints_ward_status", "complaints", ["ward_id", "status"], unique=False)
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timeline_events_complaint_id"), "timeline_events", ["complaint_id"], unique=False
    )
    op.add_column("wards", sa.Column("center_lat", sa.Float(), nullable=True))
    op.add_column("wards", sa.Column("center_lng", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wards", "center_lng")
    op.drop_column("wards", "center_lat")
    op.drop_index(op.f("ix_timeline_events_complaint_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index("ix_complaints_ward_status", table_name="complaints")
    op.drop_index("ix_complaints_department_status", table_name="complaints")
    op.drop_table("complaints")
    # ### end Alembic commands ###
