"""proof and feedback

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 17:42:04.034242

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("complaints", sa.Column("proof", sa.JSON(), nullable=True))
    op.add_column("complaints", sa.Column("feedback", sa.JSON(), nullable=True))
    op.add_column("complaints", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "resolved_at")
    op.drop_column("complaints", "feedback")
    op.drop_column("complaints", "proof")
    # ### end Alembic commands ###
